### ISSUE TITLE
time-zones

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#12]
Work with dates and times across time zones and manage changes resulting from daylight savings

**Comment by rcmoutinho** [comment]
Commit relacionado a esta issue: [45b21ba](https://github.com/duke-certification/java6-to-java8/commit/45b21ba430c929aab1c124b67d771c31d8602cb2).

**Comment by rcmoutinho** [comment]
Muito bom @rinaldodev! Se não tiver mais nenhuma alteração significativa, pode fechar a issue.

**Comment by rinaldodev** [comment]
@rcmoutinho Tem só 1 item adicional desse último commit. Se puder dar uma olhada rápida.

**Comment by rcmoutinho** [comment]
Muito bom! Fiz apenas pequenos ajustes. Finalizado.
