### ISSUE TITLE
Lambda: functional-interfaces

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#19]
Define and write functional interfaces and describe the interfaces of the java.util.function package

**Comment by rinaldodev** [comment]
@rcmoutinho está para revisão.

**Comment by rcmoutinho** [comment]
Muito bom texto e exemplos. Vou colocar algumas considerações a seguir.

_* Nunca usei e não consultei nenhum outro material para entender melhor justamente para validar o conteúdo do ebook._

Fiquei com as seguintes dúvidas:

* O retorno sempre tem que ser `void`? (no caso nunca ter retorno) _Acho que todos os exemplos ficaram como `void` e acabei ficando na dúvida se era possível ter retornos. Mais para frente, no capítulo seguinte, teve algumas coisas que mostravam que poderia ter mas isso não ficou explícito._
* Para utilizar essas interfaces funcionais eu preciso fazer uma implementação? Ou a implementação é na hora através de um lambda? Senti falta dessa clareza no texto.

Acho que ajustando essas duas dúvidas no texto já fica massa.

**Comment by rinaldodev** [comment]
@rcmoutinho coloquei mais dois exemplos que acho que ajudam com essas dúvidas, e também alterei os exemplos antigos para uma interface que faz mais sentido ser funcional.

**Comment by rcmoutinho** [comment]
Top demais @rinaldodev! Ficou muito bom mesmo! Agora não tem mais margem para dúvida porque você avisa que tem conteúdo em outro capítulo ou explica no exemplo.

Último detalhe. [Neste exemplo](https://github.com/duke-certification/java6-to-java8/blob/master/src/org/j6toj8/lambda/functionalinterfaces/FunctionalInterfaces_DefaultStatic.java), você fala sobre métodos `static` e `default`, que inclusive utilizam o método da interface funcional.

Levando em conta que ele não tem implementação ainda, como seria uma chamada desses métodos? Teria que passar algum tipo de lambda? Acho que se tiver um `main` nesse exemplo mostrando como seria a chamada ou até mesmo explicando que isso não é uma boa de fazer (realmente não sei o melhor uso) deixaria o exemplo mais rico.

**Comment by rcmoutinho** [comment]
@rinaldodev fiz poucos ajustes, se quiser pode concluir essa seção

**Comment by rinaldodev** [comment]
@rcmoutinho Ótimo! Valeu pela revisão. Fechando.
