### ISSUE TITLE
Lambda: lambda-expression

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#20]
Describe a lambda expression; refactor the code that uses an anonymous inner class to use a lambda expression; describe type inference and target typing

**Comment by rinaldodev** [comment]
@rcmoutinho pronto para revisão

**Comment by rcmoutinho** [comment]
Top! Aprendi bastante coisa!

Considerações extras:

* Um exemplo com lambda sem parenteses? [Comentei aqui.](https://github.com/duke-certification/java6-to-java8/commit/4afd9a76095db33aee58abd32e87e99470771a4d#r34138953)
* Essa [parte do código aqui](https://github.com/duke-certification/java6-to-java8/commit/4afd9a76095db33aee58abd32e87e99470771a4d#r34138977) não entendi nada... Está [nessa parte](https://github.com/duke-certification/java6-to-java8/blame/master/book/04-lambda/sections/02-lambda-expression.asc#L99) da documentação.  
Fiquei perdido aqui porque são dois métodos com retornos diferentes. Ok. Mas cada um tem um parâmetro diferente e ao chamar o método não tem parâmetro e escreve uma String... realmente me perdi nessa parte. Talvez uma explicação mais detalhada ajude a entender esse exemplo.

_* PS: Estou seguindo a mesma ideia dos outros capítulos, não estou pesquisando nada, apenas tentando entender do zero os conceitos de cada parte exclusivamente com o conteúdo do livro._

**Comment by rinaldodev** [comment]
@rcmoutinho Alterado!

Acrescentei um exemplo compilando sem a utilização de parênteses.

E alterei a parte que você citou. Veja se assim está melhor de entender. Qualquer coisa reescrevo de outra forma ou quebro em mais exemplos.

**Comment by rcmoutinho** [comment]
Massa @rinaldodev! Gostei do exemplo extra e da explicação também. Já está mais fácil de entender.

A única coisa que ainda me deixa confuso, [na mesma parte do código que tinha citado](https://github.com/duke-certification/java6-to-java8/commit/4afd9a76095db33aee58abd32e87e99470771a4d#r34138977), que agora tem 3 chamadas 😅, é quando você chama o lambda e não passa parâmetros.

Pelo que entendi ambos os métodos recebem parâmetros...

Tentando explicar isso pra ti acho que acabei entendendo. O intuito de criar os lambdas é para representar unicamente o método de cada interface. No caso um método que não tem retorno e outro que retorna uma `String`.

Quando isso está isolado (não ficam no mesmo arquivo), é feito um import para saber que esse lambda representa essa interface específica? (acho que isso não tem explicação em nenhum lugar ainda)

Veja se tem algo a melhorar na explicação depois desse depoimento (haha). Caso contrário vou tentar colocar alguma coisa expecífica que entendi aqui para você validar se faz sentido.

**Comment by rcmoutinho** [comment]
@rinaldodev fiz poucos ajustes, se quiser pode concluir essa seção

**Comment by rinaldodev** [comment]
@rcmoutinho Ótimo! Valeu pela revisão. Fechando.

**Comment by rinaldodev** [comment]
@rcmoutinho reabrindo para revisão do último commit.

**Comment by rcmoutinho** [comment]
Ficou legal a mensagem extra 👌
