### ISSUE TITLE
Lambda: built-in-interfaces

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#21]
Develop code that uses the built-in interfaces included in the java.util.function package, such as Function, Consumer, Supplier, UnaryOperator, Predicate, and Optional APIs, including the primitive and binary variations of the interfaces

**Comment by rinaldodev** [comment]
@rcmoutinho Já está disponível para revisão.

**Comment by rcmoutinho** [comment]
Muito interessante. Os exemplos ajudaram bem a entender como os métodos poderiam ser úteis. Por agora acho que já é o suficiente. Mais para frente, se acharmos outros exemplos, melhoramos/acrescentamos conteúdo.

Única dúvida que tive foi [neste linha aqui](https://github.com/duke-certification/java6-to-java8/blame/a9b7ce8a02bf704f5a1e2eb724a68fcb9d47c8a3/book/04-lambda/sections/03-built-in-interfaces.asc#L46).

Não entendi esse _custosa_, se era para ser _customizada_ ou uma função que é muito "cara" para ser executada. Veja se é necessário ajustar alguma coisa no texto.

Fora isso, pra mim ta massa. Concordando com os ajustes pode finalizar!

**Comment by rinaldodev** [comment]
Massa!

Sobre o "custosa", é a ideia de ser "muito cara" mesmo. Não achei palavra melhor, hehe. Alguma ideia?

**Comment by rcmoutinho** [comment]
Acho que teve outra parte que você colocou algo de processamento no meio. Será que "custosa em termos de processamento" já não resolveria? Eu entendi agora que é custosa mesmo mas também não tenho uma ideia para melhorar/ajustar 😅

Na dúvida acho que pode ficar assim mesmo. Acho que seria um detalhe muito específico para travar o desenvolvimento.

**Comment by rinaldodev** [comment]
Blz. Coloquei sua ideia. Fechando!

**Comment by rinaldodev** [comment]
@rcmoutinho reabrindo para revisão do último commit.

**Comment by rcmoutinho** [comment]
Ficou legal o ajuste e a mensagem mais descritiva da seção.
