### ISSUE TITLE
Lambda: method-reference

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#22]
Develop code that uses a method reference, including refactoring a lambda expression to a method reference

**Comment by rinaldodev** [comment]
@rcmoutinho Pronto para revisão.

**Comment by rcmoutinho** [comment]
@rinaldodev, bem massa essa seção! Ao mesmo tempo que ajuda essa funcionalidade, os olhos precisam estar treinados para entender alguns cenários mais específicos. Muito bom o conteúdo! Aprendi bastante! Valeu!

PS: Praticamente não teve ajuste mas fiz bastante comentário e sugestão 😜

----

O bullet inicial _"Referências a métodos de um tipo de objeto → String::isEmpty"_ já foi complexo de entender. E no exemplo dele também travei.

[Nesta parte do código](https://github.com/duke-certification/java6-to-java8/blame/9395c15d86b82c9ce923c62265384072acf48fa9/book/04-lambda/sections/04-method-reference.asc#L81), você fala novamente de `Function`. Não sei se seria interessante colocar no inicio um trecho relembrando como é esse código.

Isso porque nessa parte ficou mais complexa de entender o que o `Function` realmente faz. Explico. Nos dois exemplos anteriores, ambas as lambdas naturalmente passam valor e retornam. O exemplo é assim. Então "entendi fácil" o conceito. Mas nesse caso o método `doubleValue` não passa valor. Ai deu um nó 😅

Acho que revisando o que é o `Function` no inicio já ajude a clarear este conceito.

----

Os três primeiros exemplos você colocou _"Essa é a única chamada que essa expressão lambda faz."_ Mas para ser sincero, eu não entendi essa frase ou contexto 😅

----

Eu acho que é possível fazer chamadas com tipos diferentes, até porque alguns tem Double e String. Mas senti falta de um bullet reforçando isso, que não faz diferença o tipo que utilizar, desde que o método espere esse tipo. Não sei se seria fácil ou se conseguiria fazer algo que foge da API do Java. Pode ser legal para representar um cenário mais personalizado que o desenvolvedor pode criar.

----

Vale lembrar que neste ponto, ao final do arquivo, já imagino que a `Function` tem um método `apply`. Mas ainda sim vejo que um _source code_ no inicio pode ajudar isso a ficar ainda mais claro e fácil de entender. Eu não busquei em outra fonte para entender. E tenho quase certeza que já tinha visto isso em outro capítulo que escreveu, mas mesmo assim teria que buscar pela info.

**Comment by rinaldodev** [comment]
Então, fiz várias alterações com base nos seus comentários. Veja o que acha, se ficou mais fácil de entender algumas coisas ou não. Fiz vários reforços nas outras seções também sobre como os assuntos desse capítulo estão conectados e é muito importante compreender bem um para entender os próximos. 

Preferi não fazer resumo do que já foi dito nas outras seções, mas reforçar a necessidade de já conhecer o que falamos nas seções anteriores. Em alguns lugares deixei pra você colocar links/referências onde achar que fica legal. Caso você ainda sinta que existe essa necessidade, eu acho que prefiro voltar nas seções anteriores e incrementar com mais exemplos e explicações.

Além disso, nesta seção acrescentei mais dois bullets com exemplos adicionais. Veja se servem para elucidar a questão.

**Comment by rcmoutinho** [comment]
Caraca @rinaldodev! 😱

Ficou meeeega top as alterações que fez. Muito bom mesmo. Gostei bastante do "exemplo real" que colocou, as equivalências e observações. De fato ao rever o que é uma `Function` e `BiFunction` fica mais tranquilo de entender o _method reference_.

Última observação antes de encerrar, se é que posso pedir mais uma haha 🤪
Vi que no exemplo de `SuperHeroi`, você colocou uma forma de _method reference_ utilizando um `Suplier`, equanto em toda seção só explicou situações com `Function` e `BiFunction`. Veja se vale a pena incluir um novo _bullet_ referenciando e explicando essa situação.

Ficou MUITO bom cara! Parabéns!

**Comment by rinaldodev** [comment]
Pronto @rcmoutinho! Acrescentei a explicação, realmente acho que ficou mais claro agora!

Bom, por mim era só isso, a não ser que você tenha mais alguma sugestão. Se não, pode fechar!

**Comment by rcmoutinho** [comment]
Show @rinaldodev! Ficou melhor sim.

Eu achei que ia colocar um exemplo específico para o `Suplier`, mas acho que está bom para o momento. Com o tempo vamos acrescentando e melhorando o conteúdo.

Bora para o próximo capítulo 😄
