### ISSUE TITLE
Java Streams: using-streams

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#23]
Describe the Stream interface and pipelines; create a stream by using the Arrays.stream() and  IntStream.range() methods; identify the lambda operations that are lazy

**Comment by rinaldodev** [comment]
@rcmoutinho Tá disponível pra revisão. ;)

**Comment by rcmoutinho** [comment]
Top demais hein cara! Aprendi muita coisa nesse capítulo! 👏

Vamos aos detalhes que fiz e outros que precisam de possíveis ajustes.

**Melhorias feitas:**
* Ajustei dois tópicos que estavam separados mas com exemplos juntos, [aqui](https://github.com/duke-certification/java6-to-java8/commit/f850bbbd514f944b57f10572e7d42197e96fae97?diff=unified#diff-b506381e6233100a55852b0264daa2c4R266).
* Ajuste de plural [neste código](https://github.com/duke-certification/java6-to-java8/commit/f850bbbd514f944b57f10572e7d42197e96fae97?diff=unified#diff-e74598485d159e05bcb3feab62d9f9f0R14) (fiquei na dúvida se precisava ou não, veja o que acha).
* Diversas mudanças simples de sintax do ASC (não sei porque, mas tinham vários `*`, `_` e "`" duplicados, então só ajustei mesmo).

**Dúvidas / Necessidades:**
* [Nesta linha](https://github.com/duke-certification/java6-to-java8/commit/f850bbbd514f944b57f10572e7d42197e96fae97?diff=unified#diff-b506381e6233100a55852b0264daa2c4R36) tinha algo "perdido". Verificar se ia concluir algum raciocínio.
- **Provavelmente a única mudança relevante que preciso da sua opinião direta.** No exemplo relacionado ao `min` e `max`, na classe `Streams_MaxMinCount`, o retorno precisa obrigatoriamente ser um `Optional`? Fiquei na dúvida e uma explicação extra acho que deixaria mais claro essa questão. 
Vi que na sequencia também tem algo relacionado ao `findFirst` e `findAny` que trabalham com `Optional`. E também que mais para o final do texto fala sobre isso, na classe `Streams_Optional`, mas apenas da possibilidade de usar o `Optional` em si.

É isso! Massa demais!

**Comment by rinaldodev** [comment]
@rcmoutinho Blz! Acrescentei duas explicações sobre Optional. De resto tá tranquilo! Valeu!

**Comment by rinaldodev** [comment]
@rcmoutinho 
Cara, acabei de perceber que ficaram faltando duas partes importantes nessa seção: Streams primitivos e os Collectors. Por algum motivo achei que ficariam na próxima seção. Adicionei os tópicos, mas ainda vou fazer os exemplos. Quando eu finalizar peço uma revisão adicional dessa parte, ok? Valeu!

**Comment by rcmoutinho** [comment]
Fechado! Terminando eu reviso a explicação adicional do Optional e verifico essa parte também 😉

**Comment by rinaldodev** [comment]
@rcmoutinho  Exemplos prontos para revisão. Acho que aumentou um pouco, hehe.

**Comment by rcmoutinho** [comment]
@rinaldodev o conteúdo ficou MUITO bom 👏
Aprendi muita coisa que não fazia ideia que era possível nessa Java 8.

Fiz alguns pequenos ajustes apenas. Veja se concorda para fecharmos essa issue em seguida.
