### ISSUE TITLE
Java Streams: parallel-streams

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#24]
Develop code that uses parallel streams, including decomposition operation and reduction operation in streams

**Comment by rinaldodev** [comment]
@rcmoutinho  Pronto para revisão. ;)

**Comment by rcmoutinho** [comment]
Bem massa o conteúdo @rinaldodev! Não sabia de muita coisa dessa sessão (ou nada 🤪).

Não tive nenhuma alteração mas fiquei na dúvida [neste exemplo](https://github.com/duke-certification/java6-to-java8/blame/3af28e6d4a3fd101725cd9b763d0466d7e2136d2/book/05-java-streams/sections/02-parallel-streams.asc#L117).
Fala sobre o `findAny` mas acho que quis referenciar ao `findFirst`. Porque o método já acha qualquer coisa mesmo sem ser paralelo. No caso acho que você mostra que usando paralelo não tem garantida de conseguir mostrar o primeiro de fato.
Enfim, não alterei porque posso estar viajando e ai você me explica aqui e resolvemos.

É isso, vou gerar a versão e qualquer coisa fazemos um patch fix disso 🙂

**Comment by rinaldodev** [comment]
@rcmoutinho Fiz apenas um pequeno para mostrar o que eu realmente queria dizer. Fechando!
