### ISSUE TITLE
Concurrency: concurrent-package

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#25]
Use classes from the java.util.concurrent package including CyclicBarrier and CopyOnWriteArrayList with a focus on the advantages over and differences from the traditional java.util collections

**Comment by rinaldodev** [comment]
@rcmoutinho Seção pronta para revisão. :smiley:

**Comment by rcmoutinho** [comment]
Massa @rinaldodev! A princípio ta bem tranquilo o capítulo. Algumas coisas eu não fazia ideia mas acho que nessa sessão isso será normal de acontecer 😂

Gostei bastante do `CopyOnWriteArrayList`, sempre tinha alguma situação que tinha que fazer esse processo manualmente, deixando o código beeeem feio. Interessante saber que tem uma forma mais fácil agora.

Concordando com as alteração, só fachar 🤘

**Comment by rinaldodev** [comment]
@rcmoutinho Excelente! Valeu!
