### ISSUE TITLE
Concurrency: locks

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#26]
Use Lock, ReadWriteLock, and ReentrantLock classes in the java.util.concurrent.locks and java.util.concurrent.atomic packages to support lock-free thread-safe programming on single variables

**Comment by rinaldodev** [comment]
@rcmoutinho Pronto para revisão!

**Comment by rcmoutinho** [comment]
Show @rinaldodev! Acho que nunca usei esse lance de `locks`. Divertido aprender mais sobre.

Fiz pequenos ajustes. Concordando é só fechar! 🤘

**Comment by rinaldodev** [comment]
@rcmoutinho Ótimo! Obrigado!
