### ISSUE TITLE
Concurrency: execute-tasks

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#27]
Use Executor, ExecutorService, Executors, Callable, and Future to execute tasks using thread pools

**Comment by rinaldodev** [comment]
@rcmoutinho Seção gigante. :sleepy: Pronto para revisão! :smiley:

**Comment by rcmoutinho** [comment]
Massa @rinaldodev! Realmente estava gigante a sessão.

Algumas dúvidas:

- Não entendi muito bem [esta linha](https://github.com/duke-certification/java6-to-java8/blame/develop/book/06-concurrency/sections/03-execute-tasks.asc#L36). No caso o `shutdown` no `finally` e ainda sim ter que rodar novamente em outro lugar? Ou ter que forçar o encerramento dessas `threads` mesmo depois que o programa é finalizado? Fiquei perdido.

- [Nesse caso](https://github.com/duke-certification/java6-to-java8/blame/develop/book/06-concurrency/sections/03-execute-tasks.asc#L202) o programa só encerra depois que a tarefa agendada é executada? Ou encerra e depois é feita a execução da tarefa mesmo com o programa finalizado? (to achando que isso aqui seria conceito básico sobre threads que deixei passar, mas beleza).

Fiz peguenos ajustes além das dúvidas.

Só fico impressionado que o baeldung já escreveu praticamente sobre tudo que falamos no livro 😱

**Comment by rinaldodev** [comment]
@rcmoutinho Ajustes feitos! Valeu! :smile:
