### ISSUE TITLE
Concurrency: fork-join

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#28]
Use the parallel Fork/Join Framework

**Comment by rinaldodev** [comment]
@rcmoutinho Pronto para revisão. Da uma olhada no comentário do commit. :smile:

**Comment by rcmoutinho** [comment]
Muito louca essa sessão! Só coisa nova 😁
Valeu @rinaldodev!

Pequenos ajustes novamente.

Observações:

- Não faço a menor ideia do porque [esse console output](https://github.com/duke-certification/java6-to-java8/blame/develop/book/06-concurrency/sections/04-fork-join.asc#L35) ficou com menos 3 letras ao todo. Executei o código e mostrou tudo normalmente pra mim. Por isso esse foi um dos ajustes no texto.

**Comment by rinaldodev** [comment]
@rcmoutinho Acho que foi uma execução anterior minha que o código estava errado! Ainda bem que você viu! hehe
Valeu!
