### ISSUE TITLE
Java File I/O: paths

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#33]
Operate on file and directory paths by using the Paths class

**Comment by rcmoutinho** [comment]
Revisão de sempre. Interessante ver essa nova forma de lidar com sistema de arquivos.

Dúvidas:
- [Nesta parte](https://github.com/duke-certification/java6-to-java8/blame/develop/book/07-file-io/sections/01-paths.asc#L238), acho que está errado. No caso não pode derivar um absoluto de um relativo, e vice-versa. Certo? Pelo menos é assim que está no código acima. Vale verificar se tem algo errado.
- O que seria um path sintético? [Referência aqui](https://github.com/duke-certification/java6-to-java8/blame/develop/book/07-file-io/sections/01-paths.asc#L240).

**Comment by rinaldodev** [comment]
Corrigido!
