### ISSUE TITLE
Java File I/O: files

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#34]
Check, delete, copy, or move a file or directory by using the Files class

**Comment by rcmoutinho** [comment]
Pequenos ajustes @rinaldodev! 

Fiz a correção mesmo sabendo que não tinha comentado aqui rsrs
Se ainda estava em andamento me avisa que corrijo o que faltar 😉

**Comment by rinaldodev** [comment]
Excelente! Valeu!
