### ISSUE TITLE
Java File I/O: file-improvements

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#36]
Find a file by using the PathMatcher interface, and use Java SE 8 I/O improvements, including Files.find(), Files.walk(), and lines() methods

**Comment by rinaldodev** [comment]
@rcmoutinho Pronto para revisão!

**Comment by rcmoutinho** [comment]
Caraca meu!!! Que melhorias top!! Muito bom esse capítulo. Várias coisas super massa que ajudam demais a lidar com arquivos. Não encontrei nenhum problema também. Parabéns!
