### ISSUE TITLE
Java File I/O: watch-service

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#37]
Observe the changes in a directory by using the WatchService interface

**Comment by rinaldodev** [comment]
@rcmoutinho Pronto para revisão!

**Comment by rcmoutinho** [comment]
Pequenos ajustes! Conteúdo massa!

**Comment by rinaldodev** [comment]
@rcmoutinho Muito bom! Valeu, Rodrigo!
