### ISSUE TITLE
Java Collections: diamond

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#38]
Develop code that uses diamond with generic declarations

**Comment by rinaldodev** [comment]
@rcmoutinho Pronto pra revisão! Essa só tem um exeplo. hehe

**Comment by rcmoutinho** [comment]
Pequenos ajustes!

**Comment by rinaldodev** [comment]
Corrigido! Acrescentei mais um exemplo, ficaram os dois!
