### ISSUE TITLE
Java Collections: collections-lambda

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#39]
Develop code that iterates a collection, filters a collection, and sorts a collection by using lambda expressions

**Comment by rcmoutinho** [comment]
Pequenos ajustes!

Dúvida:
- [Nessa parte aqui](https://github.com/duke-certification/java6-to-java8/blame/develop/book/08-java-collections/sections/02-collections-lambda.asc#L13) você fala: "...pois alguns exemplos das outras exceções utilizam outros tipos de Streams.". Não seria: "...pois alguns exemplos das outras **sessões** utilizam outros tipos de Streams."? Fiquei na dúvida porque não entendi bem o que quiz dizer. Veja se to viajando.

**Comment by rcmoutinho** [comment]
A parte que tinha ficado na dúvida eu já corrigi colocando o texto na parte principal do capítulo.

**Comment by rinaldodev** [comment]
@rcmoutinho Excelente! Ainda bem que lembrou dos títulos! hehe Valeu!
