### ISSUE TITLE
Java Collections: data-search

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#40]
Search for data by using methods, such as findFirst(), findAny(), anyMatch(), allMatch(), and noneMatch()

**Comment by rinaldodev** [comment]
@rcmoutinho Pronta para revisão. Ficou pequena também. :smile: 

A mensagem de commit ficou errada e não tem o vínculo com a issue, mas é o commit 7738109cd19ebeb35f1af28cbc685680d0c7980a.

**Comment by rcmoutinho** [comment]
Revisado! Tudo ok!
