### ISSUE TITLE
Java Collections: calculations

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#41]
Perform calculations on Java Streams by using count, max, min, average, and sum methods and save results to a collection by using the collect method and Collector class, including the averagingDouble, groupingBy, joining, partitioningBy methods

**Comment by rinaldodev** [comment]
@rcmoutinho Pronto para revisão! :smile:

**Comment by rcmoutinho** [comment]
Pequeno ajuste.

Dúvida:
- [Nessa parte](https://github.com/duke-certification/java6-to-java8/blame/develop/book/08-java-collections/sections/04-calculations.asc#L73) eu acho que ficou estranho o tópico. Talvez tenha apenas duplicado por engano porque essa parte parece mais uma separação do que um concatenar como é feito no tópico anterior a esta marcação. Vale a revisão para ajustar o que for necessário.

**Comment by rinaldodev** [comment]
Corrigido!
