### ISSUE TITLE
Java Collections: collection-improvements

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#42]
Develop code that uses Java SE 8 collection improvements, including the Collection.removeIf(), List.replaceAll(), Map.computeIfAbsent(), and Map.computeIfPresent() methods

**Comment by rinaldodev** [comment]
@rcmoutinho Pronto para revisão!

**Comment by rcmoutinho** [comment]
Revisado! Bem massa esses improvements mesmo hein! Concordando com os ajustes é só fechar.

**Comment by rinaldodev** [comment]
@rcmoutinho De novo problema de copy paste. Hehe. Valeu!
