### ISSUE TITLE
Java Collections: merge-map

### ISSUE THREAD

**Issue by rcmoutinho** [duke-certification/java6-to-java8#43]
Develop  code that uses the merge(), flatMap(), and map() methods on Java Streams

**Comment by rinaldodev** [comment]
@rcmoutinho Pronto para revisão!

**Comment by rcmoutinho** [comment]
Revisado! Mas fiquei com dúvida em entender [esse tópico](https://github.com/duke-certification/java6-to-java8/blame/develop/book/08-java-collections/sections/06-merge-map.asc#L54). O que quis dizer com essa linha?

**Comment by rinaldodev** [comment]
Corrigido!
